(setf a 0)
(loop
    (setf a (+ a 1))
    (if (and (eq (% a 3) 0) (eq (% a 5) 0)) 
        (print "fizzbuzz")
        (if (eq (% a 3) 0) 
            (print "fizz")
            (if (eq (% a 5) 0)
                (print "buzz")
                (print a)
            )
        )
    )
    (if (eq a 50) abort)
)
